# Generated by Django 3.2.15 on 2022-09-08 10:52

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iin',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
            preserve_default=False,
        ),
    ]
